M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-02-26T09:08:18-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-26T09:08:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X9.0187Y-2.9445
X9.2096Y-2.9445
T2
X9.0069Y-2.8252
X9.2215Y-2.8252
M30
